### ISSUE TITLE
Feedbacks

### ISSUE THREAD

**Issue by Orion-Hunter** [felypecoliveira/CleanArch#1]
Opa mano! Como vc pediu um feedback, abri essa issue aqui.

Você ainda não tá considerando todas as camadas da Arquitetura limpa. Primeiro vc tem que entender que o domínio deve ser idependente da infraestrutura. No domínio  vc vai colocar apenas as bases do seu sistema como entidades, objetos de valor e agregados. Implementação de frameworks, bibliotecas de terceiros e etc você coloca na camada de infraestrutura. Por exemplo, vc implementa seus repositórios na camada de domínio, mas o correto seria implementá-los na camada de infra. No domínio vc pode fazer apenas as interfaces dos seus repositórios.

Pensa que o seu dominio deve ser independente da sua infra, se vc quisar colocar o seu domínio em uma outra infra vc consegue facilmente.

**Comment by Orion-Hunter** [comment]
Essa é a estrutura comum da Arquitetura limpa

![image](https://miro.medium.com/v2/resize:fit:1400/0*iU9Ks05_GTtGh6zV.jpg)

Mas vc pode usar como base as camadas da arquitetura cebola e depois ir adaptando pra limpa

![image](https://www.macoratti.net/21/05/net_onion11.jpg)

**Comment by felypecoliveira** [comment]
E ai beleza ?, vi so agora que você abriu essa issue ainda to aprendendo a mexer no Github e no git. Fiz algumas mudanças o que você achou ?. Ainda não ta completo
